[performance]
max_db_size = 10000
max_event_age = 3600

[spam_protection]
requestcredentials = true

[connections]
maxclientconnections = 100

[civkitd]
network = "testnet"
noise_port = 9735
nostr_port = 50021
cli_port = 50031

[logging]
level = "info"

[mainstay]
url = "http://localhost:4000"
position = 1
token = "14b2b754-5806-4157-883c-732baf88849c"
