[performance]
max_db_size = 10000
max_event_age = 3600

[spam_protection]
requestcredentials = true

[connections]
maxclientconnections = 100

[civkitd]
network = "testnet"
noise_port = 9735
nostr_port = 50021
cli_port = 50031

[logging]
level = "info"

[mainstay]
url = "http://localhost:4000"
position = 1
token = "14b2b754-5806-4157-883c-732baf88849c"
base_pubkey = "031dd94c5262454986a2f0a6c557d2cbe41ec5a8131c588b9367c9310125a8a7dc"
chain_code = "0a090f710e47968aee906804f211cf10cde9a11e14908ca0f78cc55dd190ceaa"

[bicoind]
host = "http://127.0.0.1"
port = 18443
rpc_user = "civkitd_client"
rpc_password = "hello_world"
